# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install root dependencies
      run: npm ci # Clean Install root dependencies

    - name: Install backend dependencies
      run: cd backend && npm ci # Clean Install backend dependencies

    - name: Install frontend dependencies
      run: cd frontend && npm ci # Clean Install frontend dependencies
      
    - name: Build project
      run: npm run build --if-present # Run build script if exist
      
    - name: Run tests
      run: npm test # Run test scripts from package.json
