# This workflow will automatically deploy the project once build.yml is completed
name: Deploy

on:
  workflow_run:
    workflows: ["Build & Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci # Clean install root dependencies
        
      - name: Install backend dependencies
        run: cd backend && npm ci # Clean install backend dependencies
        
      - name: Install frontend dependencies
        run: cd frontend && npm ci # Clean install frontend dependencies

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting